### ISSUE TITLE
action shows passing but docker build failed

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/helics-buildenv#4]
https://github.com/GMLC-TDC/helics-buildenv/runs/626539058?check_suite_focus=true

```
A    llvm/test/Transforms/PruneEH/seh-nounwind.ll
A    llvm/test/Transforms/LoopStrengthReduce/preserve-gep-loop-variant.ll
A    llvm/test/Transforms/LoopUnroll/AArch64/partial.ll
svn: E000110: Error running context: Connection timed out
The command '/bin/sh -c svn co http://llvm.org/svn/llvm-project/llvm/trunk llvm' returned a non-zero code: 1
An image does not exist locally with the tag: helics/buildenv
The push refers to repository [docker.io/helics/buildenv]
```

Not sure if this is an issue with the docker file or with the action

**Comment by nightlark** [comment]
The docker build failing is an issue with the docker file. The action runs the docker build command in a script, but that failed command isn't getting used to change the exit code from the script. I pushed a changed that will set a flag telling the script to exit with an error value if any of the changed dockerfiles from a commit fail to build (or get pushed).

**Comment by nightlark** [comment]
I triggered a build on a different image with a passing build to make sure that didn't break. Job status now accurately reflects if one (or more) docker builds/pushes failed.

**Comment by phlptp** [comment]
looks like a failure occurred when it should now
